# Site settings
title: Mathieu Mayer
email: mathieu.mm@me.com
description: The organic personal webspace of designer Mathieu Mayer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mx3m.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  things:
    ouput: true
