# Site settings
title: Mathieu Mayer
email: mathieu.mm@me.com
description: "I am a designer that wear many hats. I help organizations tell their stories, create better interactions and optimize their design operations."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mx3m.github.io" # the base hostname & protocol for your site
ga: UA-45562731-1

# Build settings
markdown: kramdown

# Permalinks
permalink: none

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  work:
    output: true

# Plugin
plugins:
- jekyll-autoprefixer
