# Site settings
title: Mathieu Mayer
email: mathieu.mm@me.com
description: The organic personal webspace of designer Mathieu Mayer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mx3m.github.io" # the base hostname & protocol for your site
ga: UA-45562731-1

# Build settings
markdown: kramdown

# Permalinks
permalink: none

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  work:
    output: true
